name: transformer_binding
version: 0.0.3
author: Man Hoang <jolleekin@outlook.com>
description: A custom binding syntax built on top of Polymer that supports transformers.
homepage: https://github.com/jolleekin/transformer_binding
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  polymer: '>=1.0.0-rc.2 <=1.0.0-rc.10'
dev_dependencies:
  browser: any
  intl: any
  reflectable: any
  web_components: any
transformers:
- web_components:
    entry_points: test/index.html
- reflectable:
    entry_points: test/index.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
